services:
  my-python-project:
    image: my-python-project:latest
    container_name: my-python-project
    build: .
    ports:
    - 8000:8000
    env_file:
      - env/app.env
    # entrypoint: /bin/sleep 3600 # use to debug 