apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_slug }}-deployment
  labels:
    app: {{ cookiecutter.project_slug }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ cookiecutter.project_slug }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_slug }}
    spec:
      containers:
      - name: {{ cookiecutter.project_slug }}
        image: docker.io/library/{{ cookiecutter.project_slug }}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: EXAMPLE
            valueFrom:
              configMapKeyRef:
                name: {{ cookiecutter.project_slug }}-config
                key: example
